# Generated by Django 5.1 on 2024-08-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_comment_timestamp_post_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="following",
            old_name="user",
            new_name="follower",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="content",
        ),
    ]
